### ISSUE TITLE
README.md update

### ISSUE THREAD

**Issue by invidia0** [andreacasalino/GaussianProcesses#9]
Hi Andrea!

Thank you for your amazing work!

In the README.md file:

``` cmake
include(FetchContent)
FetchContent_Declare(
gauss_process
GIT_REPOSITORY https://github.com/andreacasalino/GaussianProcesses
GIT_TAG        master
)
FetchContent_MakeAvailable(gauss_process)
```
the GIT_TAG **master** is now **main**.

**Comment by andreacasalino** [comment]
Dear Mattia,

Good catch! Thank you for having spotted this. Solved in 5f9b18a2a8a77b226c8068a4a822ceba4c190a03

Feel free to report any other issue,

Andrea
